services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $mailer: '@app.mailer.transactional'
            $mailchimpClient: 'csa_guzzle.client.mailchimp_api'
            $mailchimpListId: '%env(MAILCHIMP_MEMBER_LIST_ID)%'

    App\Command\:
        resource: '../../src/Command/*'
