services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $mailchimpOrgId: '%env(MAILCHIMP_ORG_ID)%'
            $mailchimpCampagnUrl: '%env(MAILCHIMP_CAMPAIGN_URL)%'
            $mailchimpWebhookKey: '%env(MAILCHIMP_WEBHOOK_KEY)%'
            $enableAssessorSpace: '%env(bool:ENABLE_ASSESSOR_SPACE)%'
            $enableMunicipalSpace: '%env(bool:ENABLE_MUNICIPAL_SPACE)%'

    App\Controller\:
        resource: ../../src/Controller/
        tags: ['controller.service_arguments']

    App\Controller\Admin\:
        resource: ../../src/Controller/Admin
        public: true
        tags: ['controller.service_arguments']
