parameters:
    env(GEO_GOUV_API_HOST): 'https://geo.api.gouv.fr'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Symfony\Contracts\HttpClient\HttpClientInterface:
            tags: ['http_client.client']

    # default http client
    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: [ 'Symfony\Component\HttpClient\HttpClient', 'create' ]

    app.http_client.mailchimp_signup:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - {base_uri: '%env(MAILCHIMP_SIGNUP_HOST)%', timeout: 15}

    app.http_client.geo_gouv:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments: [base_uri: '%env(GEO_GOUV_API_HOST)%']

    app.http_client.mandrill_api:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - {base_uri: 'https://mandrillapp.com/api/1.0/', timeout: 10}

    app.http_client.google_maps_static_api:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - {base_uri: 'https://maps.googleapis.com', timeout: 2}

    app.http_client.facebook_graph_api:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - {base_uri: 'https://graph.facebook.com', timeout: 2}

    app.http_client.mailchimp_api:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
        arguments:
            - {
                base_uri: 'https://us16.api.mailchimp.com',
                timeout: 60,
                auth_bearer: '%env(MAILCHIMP_API_KEY)%'
                headers:
                    'User-Agent': 'En-Marche!'
            }
