old_sound_rabbit_mq:
    connections:
        default:
            host: "%env(RABBITMQ_HOST)%"
            port: "%env(RABBITMQ_PORT)%"
            user: "%env(RABBITMQ_USER)%"
            password: "%env(RABBITMQ_PASSWORD)%"
            vhost: '/'
            lazy: true
            connection_timeout: 10
            read_write_timeout: 30
            heartbeat: 15

    producers:
        mailer_campaign:
            connection:       default
            exchange_options: { name: 'mailer-delayed-campaign', type: direct }
            class:            App\Producer\MailerProducer

        mailer_transactional:
            connection:       default
            exchange_options: { name: 'mailer-delayed-transactional', type: direct }
            class:            App\Producer\MailerProducer

        chezvous_algolia:
            connection:       default
            exchange_options: { name: 'chezvous_algolia', type: direct }
            class:            App\Producer\ChezVous\AlgoliaProducer

    consumers:
        mailer_campaign:
            connection:        default
            exchange_options:  { name: 'mailer-delayed-campaign', type: direct }
            queue_options:     { name: 'mailer-delayed-campaign', durable: false }
            callback:          App\Consumer\CampaignMailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        mailer_transactional:
            connection:        default
            exchange_options:  { name: 'mailer-delayed-transactional', type: direct }
            queue_options:     { name: 'mailer-delayed-transactional', durable: false }
            callback:          App\Consumer\TransactionalMailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        chezvous_algolia:
            connection:        default
            exchange_options:  { name: 'chezvous_algolia', type: direct }
            queue_options:     { name: 'chezvous_algolia', durable: false }
            callback:          App\Consumer\ChezVous\AlgoliaConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }

        mailer:
            connection:        default
            exchange_options:  { name: 'mails', type: direct }
            queue_options:     { name: 'mails', durable: false, routing_keys: [mailer.scheduled_mail] }
            callback:          App\Consumer\MailerConsumer
            qos_options:       { prefetch_size: 0, prefetch_count: 1, global: false }
