sonata_admin:
    title_logo: logo/small_bg_white.jpg
    show_mosaic_button: false
    templates:
        layout:  admin/layout.html.twig
    security:
        handler: sonata.admin.security.handler.role
    persist_filters: true
