twig:
    exception_controller: null
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/templates/TwigBundle': Twig
        '%kernel.project_dir%/templates': ~
    globals:
        app_environment: '%env(APP_ENVIRONMENT)%'
        app_version: '%env(APP_VERSION)%'
        sentry_dsn: '%env(SENTRY_DSN)%'
        recaptcha_public_key: '%env(RECAPTCHA_PUBLIC_KEY)%'
        google_maps_api_key: '%env(GMAPS_PUBLIC_API_KEY)%'
        url_legacy: 'https://adherents.en-marche.fr'
        legacy_adhesion: 'https://adherents.en-marche.fr/adherer.html'
        url_help_en_marche: 'https://aide.en-marche.fr'
        project_dir: '%kernel.project_dir%'
        mooc_host: '%env(MOOC_BASE_URL)%'
        jemengage_host: '%env(JEMENGAGE_HOST)%'
        renaissance_host: '%env(RENAISSANCE_HOST)%'
        app_renaissance_host: '%env(APP_RENAISSANCE_HOST)%'
        admin_renaissance_host: '%env(ADMIN_RENAISSANCE_HOST)%'
        national_event_host: '%env(NATIONAL_EVENT_HOST)%'
        adherent_interests: '%adherent_interests%'
        friendly_captcha_site_key: '%env(FRIENDLY_CAPTCHA_DEFAULT_SITE_KEY)%'
        friendly_captcha_europe_site_key: '%env(FRIENDLY_CAPTCHA_EUROPE_SITE_KEY)%'
        unlayer_project_id: '%env(UNLAYER_PROJECT_ID)%'
        besoindeurope_host: '%env(BESOINDEUROPE_HOST)%'
        legislative_host: '%env(LEGISLATIVE_HOST)%'
        user_vox_host: '%env(USER_VOX_HOST)%'
        mapbox_token: '%env(MAPBOX_TOKEN)%'
        mapbox_style: '%env(MAPBOX_STYLE)%'

    form_themes:
        - 'form_theme.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
