services:
    app:
        build:
            context: .
            target: php_caddy
            args:
                BUILD_DEV: true
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - enmarche.code
                    - renaissance.code
                    - admin.renaissance.code
                    - utilisateur.renaissance.code
                    - test.enmarche.code
                    - test.renaissance.code
        volumes:
            - ./:/srv/app
            - /srv/app/var/cache
            - /srv/app/var/log
            - /srv/app/var/.php_cs
            - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.ini:ro
            - caddy_data:/data
            - caddy_config:/config
            # If you develop on Mac or Windows you can remove the vendor/ directory
            # from the bind-mount for better performance by enabling the next line:
            # - /srv/app/vendor
        depends_on:
            - db
            - rabbitmq
            - redis
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://localhost/ping || exit 1']
            interval: 30s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            # See https://xdebug.org/docs/all_settings#mode
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway

    db:
        image: mysql:8.0
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7.2-alpine

    rabbitmq:
        image: rabbitmq:3-management-alpine

    node:
        build:
            context: .
            target: node
        volumes:
            - ./:/srv/app

    selenium:
        image: selenium/standalone-chrome:90.0
        shm_size: 2g

    mercure:
        image: dunglas/mercure:v0
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'https://localhost/healthz']
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - mercure_data:/data
            - mercure_config:/config

volumes:
    caddy_data:
    caddy_config:
    mercure_data:
    mercure_config:
