parameters:
    adherent_interests:
        agriculture: Agriculture
        social: Affaires sociales
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Égalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        jeunesse: Jeunesse
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        sport: Sport
        territoire: Territoire
        institution: Vie publique & institutions
