parameters:
    adherent_interests:
        agriculture: Agriculture
        social: Affaires sociales
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Egalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        jeunesse: Jeunesse
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        sport: Sport
        territoire: Territoire
        institution: Vie publique & institutions
    adherent_unregistration_reasons:
        emails: Je reçois trop d'e-mails
        soutien: J'avais uniquement adhéré pour soutenir la candidature d'Emmanuel Macron
        gouvernement: Je ne suis plus d'accord avec le gouvernement
        deputes: Je suis déçu(e) par mon/les député(e)s LaREM
        mouvement: Je suis déçu(e) par les actions du mouvement En Marche
        autre: Autre
