imports:
    - { resource: config_dev.yml }
    - { resource: assets_version.yml }

services:
    app.geocoder:
        class: 'Tests\AppBundle\Test\Geocoder\DummyGeocoder'
        public: false

    app.map.google_maps_static_provider:
        class: 'Tests\AppBundle\Test\Map\DummyStaticMapProvider'

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

    old_sound_rabbit_mq.mailer_campaign_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.mailer_transactional_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.referent_message_dispatcher_producer:
        class: 'Tests\AppBundle\Test\Producer\ReferentMessageNullProducer'

    # used for ignore check of departement for the period of testing CP only in 30 departments
    app.citizen_project.controller_subscriber:
        class: 'AppBundle\CitizenProject\CitizenProjectControllerSubscriber'
        public: false

    Tests\AppBundle\Consumer\DummyConsumer: ~

parameters:
    env(DATABASE_NAME): "enmarche_test"
    env(RECAPTCHA_PUBLIC_KEY): 'TEST_RECAPTCHA_PUBLIC_KEY'
    app_host: "test.%env(APP_HOST)%"
    amp_host: "test.%env(AMP_HOST)%"
    legislatives_host: "test.legislatives.%app_host%"
    adherent_interests:
        agriculture: Agriculture
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Egalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        institution: Vie publique & institutions
        jeunesse: Jeunesse
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        territoire: Territoire
        social: Affaires sociales
        sport: Sport
    adherent_unregistration_reasons:
        emails: Je reçois trop d'e-mails
        soutien: J'avais uniquement adhéré pour soutenir la candidature d'Emmanuel Macron
        gouvernement: Je ne suis plus d'accord avec le gouvernement
        elus: Je suis déçu(e) par mon/les élu(e)s LaREM
        mouvement: Je ne me reconnais plus dans les actions du mouvement En Marche !
        comite: Je suis en désaccord avec l’activité de mon comité local
        autre: Autre

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: 'en_marche_session_%kernel.environment%'
    profiler:
        collect: false
    cache:
        app: cache.adapter.null

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    encoders:
        AppBundle\Entity\Administrator:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
        AppBundle\Entity\Adherent:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

old_sound_rabbit_mq:
    connections:
        default:
            vhost: '/test'

    # The goal of these consumers is to create queues for the exchanges that dispatch events
    # The real consumers are in others projects like api.en-marche.fr
    consumers:
        api_user:
            connection: default
            exchange_options: { name: 'api', type: topic }
            queue_options:
                name: api_user
                routing_keys:
                    - user.created
                    - user.updated
                    - user.deleted
            callback: Tests\AppBundle\Consumer\DummyConsumer

        api_event:
            connection: default
            exchange_options: { name: 'api', type: topic }
            queue_options:
                name: api_event
                routing_keys:
                    - event.created
                    - event.updated
                    - event.deleted
            callback: Tests\AppBundle\Consumer\DummyConsumer

        api_committee:
            connection: default
            exchange_options: { name: 'api', type: topic }
            queue_options:
                name: api_committee
                routing_keys:
                    - committee.created
                    - committee.updated
                    - committee.deleted
            callback: Tests\AppBundle\Consumer\DummyConsumer
