imports:
    - { resource: config_dev.yml }
    - { resource: assets_version.yml }

services:
    app.map.google_maps_static_provider:
        class: 'Tests\AppBundle\Test\Map\DummyStaticMapProvider'

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

    old_sound_rabbit_mq.mailer_campaign_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.mailer_transactional_producer:
        class: 'Tests\AppBundle\Test\Producer\MailerNullProducer'
        public: false

    old_sound_rabbit_mq.deputy_message_dispatcher_producer:
        class: 'Tests\AppBundle\Test\Producer\DeputyMessageNullProducer'

    old_sound_rabbit_mq.chezvous_algolia_producer:
        class: 'Tests\AppBundle\Test\Producer\ChezVous\AlgoliaNullProducer'

    Tests\AppBundle\Consumer\DummyConsumer: ~

    Tests\AppBundle\Test\Payment\PayboxProvider:
        arguments:
            - '%env(SSL_PRIVATE_KEY)%'

    AppBundle\Messenger\MessageRecorder\MessageRecorderInterface:
        alias: AppBundle\Messenger\MessageRecorder\MessageRecorder

    test.AppBundle\Adherent\Handler\RemoveAdherentAndRelatedDataCommandHandler:
        alias: AppBundle\Adherent\Handler\RemoveAdherentAndRelatedDataCommandHandler
        public: true

parameters:
    env(DATABASE_NAME): "enmarche_test"
    env(RABBITMQ_DSN): 'amqp://%env(RABBITMQ_USER)%:%env(RABBITMQ_PASSWORD)%@%env(RABBITMQ_HOST)%:%env(RABBITMQ_PORT)%/%2f?lazy=0&connection_timeout=10&read_write_timeout=200&heartbeat=100'
    env(RECAPTCHA_PUBLIC_KEY): 'TEST_RECAPTCHA_PUBLIC_KEY'
    env(GMAPS_API_KEY):
    app_host: "test.%env(APP_HOST)%"
    amp_host: "test.%env(AMP_HOST)%"
    legislatives_host: "test.legislatives.%app_host%"
    adherent_unregistration_reasons:
        emails: Je reçois trop d'e-mails
        soutien: J'avais uniquement adhéré pour soutenir la candidature d'Emmanuel Macron
        gouvernement: Je ne suis plus d'accord avec le gouvernement
        elus: Je suis déçu(e) par mon/les élu(e)s LaREM
        mouvement: Je ne me reconnais plus dans les actions du mouvement En Marche !
        comite: Je suis en désaccord avec l’activité de mon comité local
        autre: Autre

    messenger.middleware:
        - { id: AppBundle\Messenger\RecorderMiddleware }
        - { id: send_message }
        - { id: handle_message }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: 'en_marche_session_%kernel.environment%'
    profiler:
        collect: false
    cache:
        app: cache.adapter.null

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    encoders:
        AppBundle\Entity\Administrator:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
        AppBundle\Entity\Adherent:
            algorithm: md5
            encode_as_base64: false
            iterations: 0

old_sound_rabbit_mq:
    connections:
        default:
            vhost: '/test'
            read_write_timeout: 40
            heartbeat: 20

    # The goal of these consumers is to create queues for the exchanges that dispatch events
    # The real consumers are in others projects like api.en-marche.fr
    consumers:
        api_sync:
            connection: default
            exchange_options: { name: 'api', type: topic }
            queue_options:
                name: api_sync
                routing_keys:
                    - user.*
                    - event.*
                    - committee.*
                    - citizen_action.*
                    - citizen_project.*
            callback: Tests\AppBundle\Consumer\DummyConsumer

lexik_paybox:
    public_key: "%env(SSL_PUBLIC_KEY)%"

doctrine:
    dbal:
        connections:
            default:
                logging: false
                profiling: false

api_platform:
    enable_entrypoint: false
    collection:
        pagination:
            items_per_page: 2
