imports:
    - { resource: config_dev.yml }

services:
    app.geocoder:
        class: 'Tests\AppBundle\Test\Geocoder\DummyGeocoder'
        public: false

    app.map.google_maps_static_provider:
        class: 'Tests\AppBundle\Test\Map\DummyStaticMapProvider'

    app.glide.cache_adapter:
        class: 'League\Flysystem\Memory\MemoryAdapter'

    old_sound_rabbit_mq.mailjet_campaign_producer:
        class: 'Tests\AppBundle\Test\Producer\MailjetNullProducer'
        public: false

    old_sound_rabbit_mq.mailjet_transactional_producer:
        class: 'Tests\AppBundle\Test\Producer\MailjetNullProducer'
        public: false

    old_sound_rabbit_mq.referent_message_dispatcher_producer:
        class: 'Tests\AppBundle\Test\Producer\ReferentMessageNullProducer'

parameters:
    env(DATABASE_NAME): "enmarche_test"
    adherent_interests:
        agriculture: Agriculture
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Egalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        institution: Vie publique & institutions
        jeunesse: Jeunesse
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        territoire: Territoire
        social: Affaires sociales
        sport: Sport

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: 'en_marche_session_%kernel.environment%'
    profiler:
        collect: false
    cache:
        app: cache.adapter.null

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    encoders:
        AppBundle\Entity\Administrator:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
        AppBundle\Entity\Adherent:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
