imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assets_version.yml }
    - { resource: services/admin.xml }
    - { resource: services/content.xml }
    - { resource: services/cloudflare.xml }
    - { resource: services/doctrine.xml }
    - { resource: services/donation.xml }
    - { resource: services/intl.xml }
    - { resource: services/invitation.xml }
    - { resource: services/mailjet.xml }
    - { resource: services/media.xml }
    - { resource: services/membership.xml }
    - { resource: services/recaptcha.xml }
    - { resource: services/security.xml }
    - { resource: services/storage.xml }
    - { resource: services/twig.xml }

parameters:
    locale: fr
    pattern_uuid: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
    pattern_sha1: '[0-9A-Fa-f]{40}'
    sender_email: 'contact@en-marche.fr'
    sender_name:  'En Marche !'

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name:        enmarche
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        assets_hash:          "%assets_hash%"
        sentry_dsn:           "%env(SENTRY_PUBLIC_DSN)%"
        recaptcha_public_key: "%env(RECAPTCHA_PUBLIC_KEY)%"
    form_themes:
        - 'form_theme.html.twig'

doctrine:
    dbal:
        driver:           pdo_mysql
        charset:          UTF8
        host:             "%env(DATABASE_HOST)%"
        port:             "%env(DATABASE_PORT)%"
        dbname:           "%env(DATABASE_NAME)%"
        user:             "%env(DATABASE_USER)%"
        password:         "%env(DATABASE_PASSWORD)%"
        unix_socket:      "%env(DATABASE_SOCKET)%"
        server_version:   5.7

        types:
            uuid:           Ramsey\Uuid\Doctrine\UuidType
            phone_number:   Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Migrations
    table_name: migrations
    name: En Marche migrations

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            sluggable: true
            softdeleteable: true
            timestampable: true

lexik_paybox:
    parameters:
        production:  false
        site:        "%env(PAYBOX_SITE)%"
        rank:        "%env(PAYBOX_RANK)%"
        login:       "%env(PAYBOX_IDENTIFIER)%"
        hmac:
            key:     "%env(PAYBOX_KEY)%"

fos_js_routing:
    cache_control:
        public: true
        smaxage: 31536000   # 1 year, to be purged using Cloudflare

csa_guzzle:
    profiler: '%kernel.debug%'
    logger: true
    clients:
        mailjet_api:
            config:
                base_uri: 'https://api.mailjet.com/v3/'
                timeout: 2.0
                headers:
                    Content-Type: 'application/json'

        cloudflare_api:
            config:
                base_uri: 'https://api.cloudflare.com/client/v4/zones/%env(CLOUDFLARE_ZONE_ID)%'
                timeout: 2.0
                headers:
                    Content-Type: 'application/json'

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title_logo: logo/small_bg_white.jpg
    templates:
        layout:  admin/layout.html.twig
    security:
        handler: sonata.admin.security.handler.role

