#
# Oauth client
#
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

auth_login_check:
    path: /login/check-auth
    methods: [GET]

auth_logout:
    path: /logout
    methods: [GET]

#
# Health
#
app_health:
    host:     "%app_host%"
    resource: "@AppBundle/Controller/HealthController.php"
    type:     "annotation"

#
# Assets
#
app_assets:
    schemes:  [https]
    host:     "%app_host%"
    resource: "@AppBundle/Controller/AssetsController.php"
    type:     "annotation"

#
# API
#
app_api:
    host:     "%app_host%"
    resource: "@AppBundle/Controller/Api"
    type:     "annotation"
    prefix:   "/api"

#
# Admin panel
#
admin_dashboard:
    host:     "%app_host%"
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   "/admin"

admin_crud:
    host:     "%app_host%"
    resource: .
    type:     sonata_admin
    prefix:   "/admin"

app_admin:
    host:     "%app_host%"
    resource: "@AppBundle/Controller/Admin"
    type:     "annotation"
    prefix:   "/admin"

#
# En Marche app
#
lexik_paybox:
    host:     "%app_host%"
    resource: "@LexikPayboxBundle/Resources/config/routing.yml"
    prefix:   "/don"

# This route must be loaded first to prevent an override
map_events:
    path: /evenements/la-carte
    methods: GET
    defaults: { _controller: 'AppBundle:EnMarche/Map:events' }
    condition: "not (context.getHost() matches '/legislatives/i')"

app_enmarche:
    host:     "%app_host%"
    resource: "@AppBundle/Controller/EnMarche"
    type:     "annotation"

#
# AMP pages
#
app_enmarche_amp:
    host:     "%amp_host%"
    resource: "@AppBundle/Controller/Amp"
    type:     "annotation"

#
# Legislatives app
#
app_legislatives:
    host:     "%legislatives_host%"
    resource: "@AppBundle/Controller/Legislatives"
    type:     "annotation"

#
# Legacy
#
app_desintox:
    host: "%app_host%"
    path: /emmanuel-macron/desintox/{slug}
    defaults:
        slug: ~
        _controller: FrameworkBundle:Redirect:redirect
        route: ~

#
# Redirections
#
app_redirecting:
    host:     "%app_host%"
    resource: "@AppBundle/Controller/RedirectingController.php"
    type:     "annotation"
