name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-16.04

    steps:
        # switch php version to 7.3
        -   name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: '7.3'

        -   name: Checkout repository
            uses: actions/checkout@v2

        # Cache node_modules and install yarn packages
        -   name: Cache node_modules
            uses: actions/cache@v2
            with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                ${{ runner.os }}-modules-

        -   name: Set up yarn dependencies
            run: yarn install

        # Cache and install PHP dependencies
        -   name: Cache vendor
            uses: actions/cache@v2
            id: vendor-cache
            with:
              path: vendor
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                ${{ runner.os }}-composer-

        -   name: Install composer dependencies
            if: steps.vendor-cache.outputs.cache-hit != 'true'
            run: composer install --prefer-dist --no-progress

        # Cache phpstan-tmp dir and run js, php and yaml lint test
        -   name: Cache phpstan
            uses: actions/cache@v2
            with:
              path: ./var/phpstan-tmp
              key: ${{ runner.os }}-phpstan-${{ hashFiles('**/phpstan.neon.dist') }}
              restore-keys: |
                ${{ runner.os }}-phpstan-

        -   name: make php-cs-fixer and phpstan analyse
            run: |
              set -x
              php -d memory_limit=1024m vendor/bin/php-cs-fixer fix --diff --dry-run --no-interaction -v
              vendor/bin/phpstan analyse

        -   name: make console lint
            run: |
              set -x
              bin/console lint:yaml config --parse-tags
              bin/console lint:twig templates
              bin/console lint:container

        -   name: make JS lint
            run: |
              set -x
              yarn lint
